name: ACME Courier
version: 1.2.0
slug: acme-courier
description: Obtain Let's Encrypt certificates through Namecheap DNS and deploy them locally or over SSH
arch:
  - aarch64
  - amd64
url: https://github.com/skateman/hh-hassio-repo
options:
  draft: false
  acme:
    email_account: null
    crontab_renew: "12 01 * * *"
    directory_url: ""
    staging: false
    renew_before_days: 30
    renew_jitter: "30m"
  namecheap:
    auth_username: null
    auth_token: null
    auth_client_ip: "127.0.0.1"
    proxy: ""
    ttl: 120
    propagation_timeout: "1h"
    polling_interval: "15s"
  certificates: []
schema:
  draft: bool
  acme:
    email_account: email
    crontab_renew: str
    directory_url: str
    staging: bool
    renew_before_days: "int(1,89)"
    renew_jitter: str
  namecheap:
    auth_username: str
    auth_token: password
    auth_client_ip: str
    proxy: password
    ttl: "int(1,86400)"
    propagation_timeout: str
    polling_interval: str
  certificates:
    - name: str
      domains:
        - str
      force_renew: "bool?"
      reuse_key: "bool?"
      key_type: "list(rsa|ecdsa)?"
      deploy:
        - path: str
          identity_file: "str?"
          known_hosts_file: "str?"
          port: "int(1,65535)?"
          files:
            - "list(cert.pem|chain.pem|fullchain.pem|privkey.pem)?"
      restart_apps:
        - "str?"
breaking_versions:
  - 1.1.0
startup: application
apparmor: true
hassio_api: true
hassio_role: manager
init: false
boot: auto
image: ghcr.io/skateman/hh-hassio-repo/{arch}-acme-courier
map:
  - type: ssl
    read_only: false
  - type: addon_config
    read_only: false
    path: /config
host_network: false
