name: Deploy to the GitHub Packages Container Registry
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          docker run --privileged homeassistant/amd64-builder       \
            --armhf                                                 \
            --target audio-player                                   \
            --repository https://github.com/skateman/hh-hassio-repo \
            --branch master                                         \
            --docker-hub ghcr.io                                    \
            --docker-user skateman                                  \
            --docker-password ${{ secrets.GITHUB_TOKEN }}
