name: Deploy to the GitHub Packages Container Registry
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          cat /etc/docker/daemon.json | jq --arg drv overlay2 '. + {"storage-driver": $drv}' > /etc/docker/daemon.json
          sudo service docker restart
          docker run --privileged -e DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }} -v `pwd`:/data homeassistant/amd64-builder \
            --armhf                                           \
            --target /data/audio-player                       \
            --branch master                                   \
            --docker-hub ghcr.io/skateman                     \
            --docker-user skateman
