name: Deploy to the GitHub Packages Container Registry
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                releases(first:1) {
                  nodes {
                    name
                    createdAt
                    tagName
                    description
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"


      - run: |
          # Set the docker storage driver to aufs
          cat /etc/docker/daemon.json | jq --arg drv aufs '. + {"storage-driver": $drv}' | sudo tee /etc/docker/daemon.json > /dev/null

          # Restart the docker daemon
          sudo service docker restart

          # Docker registry login
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login docker.pkg.github.com -u skateman --password-stdin

          # Build and publish the container
          # docker run --rm --privileged -v `pwd`:/data           \
          #   -v `pwd`:/data -v ~/.docker:/root/.docker           \
          #   homeassistant/amd64-builder                         \
          #   --armhf                                             \
          #   --target /data/audio-player                         \
          #   --image skateman/hh-hassio-repo/{arch}-audio-player \
          #   --branch master                                     \
          #   --docker-hub docker.pkg.github.com